#!/bin/sh
#
# Commit Message Hook (Fallback for Non-Node Projects)
# Generated by git-repo-init skill
#
# Validates commit messages follow conventional commit format.
# Place in: .git/hooks/commit-msg
# Make executable: chmod +x .git/hooks/commit-msg
#
# Format: <type>(<scope>): <subject>
# Example: feat(auth): add password reset flow

# Read the commit message from the file
commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

# Get the first line (header)
header=$(echo "$commit_msg" | head -n1)

# Skip merge commits
if echo "$header" | grep -qE "^Merge "; then
  exit 0
fi

# Skip revert commits
if echo "$header" | grep -qE "^Revert "; then
  exit 0
fi

# Allowed types
types="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"

# Pattern: type(scope): subject  OR  type: subject
# - Type is required and must be from allowed list
# - Scope is optional
# - Colon and space after type/scope is required
# - Subject is required and must start with lowercase
pattern="^($types)(\([a-z0-9_-]+\))?: [a-z]"

if ! echo "$header" | grep -qE "$pattern"; then
  echo ""
  echo "❌ Invalid commit message format!"
  echo ""
  echo "Your message:"
  echo "  $header"
  echo ""
  echo "Expected format:"
  echo "  <type>(<scope>): <subject>"
  echo ""
  echo "Examples:"
  echo "  feat(auth): add password reset flow"
  echo "  fix: resolve null pointer exception"
  echo "  docs(readme): update installation instructions"
  echo ""
  echo "Allowed types:"
  echo "  feat     - New feature"
  echo "  fix      - Bug fix"
  echo "  docs     - Documentation only"
  echo "  style    - Formatting, no code change"
  echo "  refactor - Code restructuring"
  echo "  perf     - Performance improvement"
  echo "  test     - Adding or correcting tests"
  echo "  build    - Build system or dependencies"
  echo "  ci       - CI configuration"
  echo "  chore    - Maintenance tasks"
  echo "  revert   - Revert a previous commit"
  echo ""
  echo "Rules:"
  echo "  - Type must be lowercase"
  echo "  - Subject must start with lowercase letter"
  echo "  - No period at end of subject"
  echo "  - Header max 100 characters"
  echo ""
  exit 1
fi

# Check header length
header_length=${#header}
if [ "$header_length" -gt 100 ]; then
  echo ""
  echo "❌ Commit message header too long!"
  echo ""
  echo "Current length: $header_length characters"
  echo "Maximum length: 100 characters"
  echo ""
  exit 1
fi

# Check that subject doesn't end with period
if echo "$header" | grep -qE "\.$"; then
  echo ""
  echo "❌ Commit message subject should not end with a period!"
  echo ""
  echo "Your message: $header"
  echo ""
  exit 1
fi

# All checks passed
exit 0
